query GetNewsletterModalConfig @context(scope: "private") {
  getNewsletterModalConfig {
    modalTitle
    modalDescription
    modalTextSuccess
    modalEnabled
    modalShowRule
    modalShowWhen
  }
}
